name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        jenkins-version: [2.60.3, lts]

    services:
      jenkins:
        image: jenkins/jenkins:${{ matrix.jenkins-version }}
        ports:
          - 8080:8080
        options: --name jenkins

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Get Jenkins initial password
      run: |
        sleep 10
        echo ::set-env name=login::Admin
        echo ::set-env name=password::$(docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword)

    - name: Test with pytest
      run: |
        pip install pytest pytest-cov pytest-asyncio coveralls
        pytest -v --cov=aiojenkins --cov-report=term
        COVERALLS_REPO_TOKEN=${{ secrets.coveralls }} coveralls
