on: ['push', 'pull_request']
name: Tests
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.5', '3.6', '3.7', '3.8', '3.9', '3.10']
        jenkins-version: ['jenkins:1.554', 'jenkins/jenkins:2.60', 'jenkins/jenkins:2.319']

    services:
      jenkins:
        image: ${{ matrix.jenkins-version }}
        ports:
          - 8080:8080
        options: --name jenkins

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox coveralls

    - name: Get Jenkins initial password
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: |
        sleep 10
        echo ::set-env name=login::Admin
        echo ::set-env name=password::$(docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword)
        docker exec jenkins jenkins-plugin-cli --plugins cloudbees-folder || true
        docker restart jenkins
        sleep 5

    - name: Testing with tox
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
      run: |
        tox
        COVERALLS_REPO_TOKEN=${{ secrets.coveralls }} COVERALLS_PARALLEL=true coveralls

  finish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls finished
      run: |
        curl https://coveralls.io/webhook?repo_token=${{ secrets.coveralls }} -d "payload[build_num]=${{ github.sha }}&payload[status]=done"
